### 차단 통계 조회 (차단 내역이 있는 사용자)
GET {{host}}/api/v1/test/block/statistics/1
Content-Type: application/json

### 차단 통계 조회 (차단 내역이 없는 사용자)
GET {{host}}/api/v1/test/block/statistics/10
Content-Type: application/json

### 차단 통계 조회 (많은 차단 내역이 있는 사용자)
GET {{host}}/api/v1/test/block/statistics/2
Content-Type: application/json

### 차단 통계 조회 (존재하지 않는 사용자)
GET {{host}}/api/v1/test/block/statistics/999
Content-Type: application/json