### 토큰 발급
POST {{host}}/api/v1/oauth/login
Content-Type: application/json

{
  "email": "dev.bottle-note_test@gmail.com",
  "socialType": "GOOGLE",
  "gender": "MALE",
  "age": 25
}
> {%
    //토큰을 전역변수로 저장
    client.global.set("accessToken", response.body.data.accessToken);
%}


### 위스키  찜하기
PUT  {{host}}/api/v1/picks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "alcoholId": 1,
    "isPicked": "PICK"
}

### 둘러보기 조회
@userId = 16
GET {{host}}/api/v1/my-page/{{userId}}/my-bottle/picks
Content-Type: application/json
Authorization: Bearer {{accessToken}}
