version: "3.9"
services:
  dev-bottle-note:
    build:
      context: .
      dockerfile: build.Dockerfile
    container_name: dev-bottle-note
    ports:
      - "30001:30001"
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=dev
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
