version: "3.9"
services:
  dev-bottle-note:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-bottle-note
    ports:
      - "30001:30001"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
