version: "3.9"
services:
  mysql:
    image: mysql:8.0
    hostname: bottle-note-mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: bottle_note
      MYSQL_USER: bottle_note
      MYSQL_PASSWORD: bottle_note_1234
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql/config:/etc/mysql/conf.d
      - ./database/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - network

  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    #volumes:
    #  - ./database/redis/data:/data
    #  - ./database/redis/conf/redis.conf:/usr/local/conf/redis.conf
    networks:
      - network

    # 설정파일이 필요하면 추후 각 Local에 아래 경로에 추가해야 합니다.
    #https://github.com/gingaminga/docker-redis/blob/main/redis.conf
    #command: redis-server /usr/local/etc/redis/redis.conf
networks:
  network:
    driver: bridge
