#act workflow_dispatch -W .github/workflows/act/1password.yml --secret-file .secrets --container-architecture linux/arm64
name: 1Password Environment File Masking

on:
  workflow_dispatch:

jobs:
  mask-secrets:
    name: Mask Secrets from .env Content (Console Only)
    runs-on: ubuntu-latest

    steps:
      - name: 1Password 서비스 계정 설정
        uses: 1password/load-secrets-action/configure@v2
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: SSH 자격증명 및 환경변수 로드
        uses: 1password/load-secrets-action@v2
        id: op-load-server-secret
        with:
          export-env: true
          unset-previous: false
        env:
          SERVER_IP: op://vault/product-cluster-1/ip
          SERVER_PORT: op://vault/product-cluster-1/port
          SERVER_NAME: op://vault/product-cluster-1/user name
          SSH_KEY: op://vault/product-cluster-ssh-key/private_key?ssh-format=openssh
          PROD_ENV: op://vault/.env.prod/.env.prod

      - name:  SSH 연결 및 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          port: ${{ env.SERVER_PORT }}
          username: ${{ env.SERVER_NAME }}
          key: ${{ env.SSH_KEY }}
          script: |
            # 환경 변수 파일 설정 (1Password에서 직접 로드된 내용 사용)
            echo "${{ env.PROD_ENV }}" > .bottlenote.production.ENV
