server:
  port: 8080 # to be changed some other port number
  encoding:
    charset: UTF-8 # 인코딩 설정
  version: 0.0.1
  path:
    version: /v1


# DB properties
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bottle_note?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: bottle_note
    password: bottle_note_1234

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        show_sql: false
        use_sql_comments: false
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379
  sleuth:
    jdbc:
      p6spy:
        tracing:
          include-parameter-values: true


# p6spy 설정 추가
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j


# Logging
logging:
  level:
    root: info
    org.hibernate.orm.jdbc.bind: trace

# Spring Security
security:
  jwt:
    secret-key: 'c2VjdXJlU2VjcmV0S2V5MTIzNDU2Nzg5MGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6QWJDRGVGR2hJSktMTU5PUFFSU1RVVldYWVphYmNkZWZnaGlrSg=='


# AWS S3
amazon:
  aws:
    accessKey: ${AMAZON_AWS_ACCESS_KEY:AMAZON_AWS_ACCESS_KEY}
    secretKey: ${AMAZON_AWS_SECRET_KEY:AMAZON_AWS_SECRET_KEY}
    region: ${AMAZON_AWS_REGION:AMAZON_AWS_REGION}
    bucket: ${AMAZON_AWS_BUCKET:AMAZON_AWS_BUCKET}
    cloudFrontUrl: ${AMAZON_AWS_CLOUDFRONT_URL:AMAZON_AWS_CLOUDFRONT_URL}

profanity:
  filter:
    url: https://api.profanity-filter.run/api/v1
    key: ${PROFANITY_FILTER_KEY:PROFANITY_FILTER_KEY}
