server:
  port: 8080 # to be changed some other port number
  encoding:
    charset: UTF-8 # 인코딩 설정
  version: 0.0.1
  path:
    version: /v1


# DB properties
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #TODO : 추후 운영환경의 datasource로 수정 필요
    url: jdbc:mysql://localhost:43306/bottle_note?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: bottle_note
    password: bottle_note_1234
  jpa:
    hibernate:
      ddl-auto: validate # validate, update, create, create-drop
    properties:
      hibernate:
        format_sql: true # SQL 출력 포맷
    open-in-view: false # JPA 영속성 컨텍스트를 View까지 열어두는 옵션 (default: true) - false로 설정할 것
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    root: info # error, warn, info, debug, trace (default: info)


security:
  jwt: # dummy-key : 로그인 개발용으로 만든 더미키 입니다. 실제 서비스에서는 키값도 변경해야하며, 노출되지않는 application.yml에 넣어야 합니다.
    secret-key: 'c2VjdXJlU2VjcmV0S2V5MTIzNDU2Nzg5MGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6QWJDRGVGR2hJSktMTU5PUFFSU1RVVldYWVphYmNkZWZnaGlrSg=='
