# TODO : java -jar test-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod

spring:
  profiles:
    default: local
  jackson:
    time-zone: Asia/Seoul
---
spring:
  config:
    activate:
      on-profile: local,dev,prod
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

decorator:
  datasource:
    p6spy:
      enable-logging: false # p6spy 로깅 활성화

## Spring Boot Actuator 공통 설정
management:
  endpoints:
    web:
      exposure:
        include: [ "health", "prometheus" ]
      base-path: /system/actuator
  endpoint:
    health:
      show-details: always
server:
  tomcat:
    mbeanregistry:
      enabled: true

app:
  thirdParty:
    firebase-configuration-file: /home/ubuntu/fcm/service_account_credentials.json
