server:
  port: 8080 # to be changed some other port number
  encoding:
    charset: UTF-8 # 인코딩 설정
  version: 0.0.1
  path:
    version: /v1


# DB properties
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bottle_note?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: bottle_note
    password: bottle_note_1234
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: 46a2ada90428bb4f3b487d7672f3438c
            client-secret: jBa14GLyVVOfcZTrB7lvlhW7Y9snqYQN
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname

  jpa:
    hibernate:
      ddl-auto: validate # validate, update, create, create-drop
    properties:
      hibernate:
        format_sql: true # SQL 출력 포맷
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false # JPA 영속성 컨텍스트를 View까지 열어두는 옵션 (default: true) - false로 설정할 것
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    redis:
      host: localhost
      port: 6379


logging:
  level:
    root: info # error, warn, info, debug, trace (default: info)


security:
  jwt: # dummy-key : 로그인 개발용으로 만든 더미키 입니다. 실제 서비스에서는 키값도 변경해야하며, 노출되지않는 application.yml에 넣어야 합니다.
    secret-key: 'c2VjdXJlU2VjcmV0S2V5MTIzNDU2Nzg5MGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6QWJDRGVGR2hJSktMTU5PUFFSU1RVVldYWVphYmNkZWZnaGlrSg=='
