# application-logging.yml
logging:
  level:
    root: info

--- # Local 환경
spring:
  config:
    activate:
      on-profile: local
  sleuth:
    jdbc:
      p6spy:
        tracing:
          include-parameter-values: true
logging:
  level:
    root: info
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.SQL: debug
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j

--- # 개발 환경
spring:
  config:
    activate:
      on-profile: dev
  sleuth:
    jdbc:
      p6spy:
        tracing:
          include-parameter-values: true
logging:
  level:
    root: info
    org.hibernate.orm.jdbc.bind: info
    org.hibernate.SQL: info
  file:
    name: /app/logs/application-dev.log  # 이미 마운트된 볼륨 경로와 일치
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j

--- # 운영 환경
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        use_sql_comments: false
logging:
  level:
    root: info
    org.hibernate: info
  file:
    name: /app/logs/application-prod.log  # 이미 마운트된 볼륨 경로와 일치
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 30
      total-size-cap: 10GB
decorator:
  datasource:
    p6spy:
      enable-logging: false
