# TODO : java -jar test-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod

spring:
  profiles:
    default: dev
---
spring:
  config:
    activate:
      on-profile: local,dev,prod
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

## Spring Boot Actuator 공통 설정
management:
  endpoints:
    web:
      exposure:
        include: [ "health", "prometheus" ]
      base-path: /system/actuator
  endpoint:
    health:
      show-details: always

server:
  tomcat:
    mbeanregistry:
      enabled: true # actuator에 mbean 정보 노출
