### 토큰 발급
POST {{host}}/api/v1/oauth/login
Content-Type: application/json

{
  "email": "dev.bottle-note@gmail.com",
  "socialType": "GOOGLE",
  "gender": "MALE",
  "age": 25
}

> {%
    //토큰을 전역변수로 저장
    client.global.set("accessToken", response.body.data.accessToken);
%}

### 별점 목록 조회
GET http://localhost:8081/api/v1/rating?keyword=YAM&category=&regionId=&sortType=RANDOM&sortOrder=DESC&cursor=&pageSize=
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### 별점 목록 조회
GET http://localhost:8081/api/v1/rating
Content-Type: application/json
Authorization: Bearer ""

{
  "keyword": "YAM",
  "category": "",
  "regionId": "",
  "sortType": "RANDOM",
  "sortOrder": "DESC",
  "cursor": "",
  "pageSize": ""
}
