POST {{host}}/api/v1/oauth/login
Content-Type: application/json

{
  "email": "juye@gmail.com",
  "socialType": "GOOGLE",
  "gender": "",
  "age": ""
}

###
GET {{host}}/api/v1/alcohols/categories
Content-Type: application/json
Authorization: Bearer {{accessToken}}
