@token = Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoeWVqajE5QG5hdmVyLmNvbSIsInJvbGVzIjoiUk9MRV9VU0VSIiwidXNlcklkIjoxLCJpYXQiOjE3MzEyMDg0NTMsImV4cCI6MTczMTIwODUxM30.sBW0m-3vdIA0wJJkshFjlC2tGNU_ZfjfNwCP1tieL-8v-8LuNcGGu7XPrSZLzf8odVrNAqWyFK_7CeMV8iIIsA
@empty_token = Bearer


###  유저 아이디가 필수인 경우
GET {{host}}/api/v1/my-page/8/my-bottle?keyword=&regionId=&tabType=ALL&sortType=LATEST&sortOrder=DESC&cursor=0&
    pageSize=50
Content-Type: application/json
Authorization: {{empty_token}}


### 유저 아이디가 만료된 경우.
GET {{host}}/api/v1/my-page/8/my-bottle?keyword=&regionId=&tabType=ALL&sortType=LATEST&sortOrder=DESC&cursor=0&
    pageSize=50
Content-Type: application/json
Authorization: {{token}}

### 필수는 아니지만 토큰이 없는 경우
GET {{host}}/api/v1/popular/week
Content-Type: application/json
Authorization: {{empty_token}}

### 필수가 아니지만 토큰이 만료된 경우
GET {{host}}/api/v1/popular/week
Content-Type: application/json
Authorization: {{token}}
