### 토큰 발급
POST {{host}}/api/v1/oauth/login
Content-Type: application/json

{
  "email": "juye@gmail.com",
  "socialType": "GOOGLE",
  "gender": "",
  "age": ""
}

> {%
    //토큰을 전역변수로 저장
    client.global.set("accessToken", response.body.data.accessToken);
%}


### 팔로우 조회 진행한다.
GET  {{host}}/api/v1/follow/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "cursor": 0,
  "pageSize": 50
}
