### 토큰 발급 (일반)
POST {{host}}/api/v1/oauth/login
Content-Type: application/json

{
  "email": "dev.bottle-note@gmail.com",
  "socialType": "GOOGLE",
  "gender": "MALE",
  "age": 25
}

> {%
    //토큰을 전역변수로 저장
    client.global.set("accessToken", response.body.data.accessToken);
%}

### 위스키 둘러보기
GET {{host}}/api/v1/alcohols/explore/standard?cursor=0&size=6&keywords=탈라모어&keywords=사과
Authorization: Bearer {{accessToken}}

### 위스키 둘러보기 2
GET {{host}}/api/v1/alcohols/explore/standard?cursor=0&size=10
Authorization: Bearer {{accessToken}}

