### 토큰 발급 (일반)
POST {{host}}/api/v1/oauth/login
Content-Type: application/json

{
  "email": "dev.bottle-note@gmail.com",
  "socialType": "GOOGLE",
  "gender": "MALE",
  "age": 25
}

> {%
    //토큰을 전역변수로 저장
    client.global.set("accessToken", response.body.data.accessToken);
%}

### 토큰이 없을 경우 발생하는 예외 예제
PUT http://localhost:15000/api/v1/picks
Content-Type: application/json

{
  "alcoholId": 1,
  "isPicked": "PICK"
}
