spring:
  application:
    name: ${OTEL_SERVICE_NAME:UNKNOWN_SERVICE}

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "metrics", "prometheus", "tracing" ]
      base-path: /actuator
  endpoint:
    health:
      show-details: always

  # OpenTelemetry 트레이싱
  tracing:
    propagation:
      consume: W3C, B3, B3_MULTI
      produce: W3C
    disabled: ${OTEL_TRACING_DISABLED:false}  # false = 트레이싱 활성화
    sampling:
      probability: ${OTEL_TRACE_SAMPLING:1.0}

  # OTLP 설정
  otlp:
    # Traces 설정 (Tempo)
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT}
      timeout: ${OTEL_EXPORTER_OTLP_TIMEOUT:10s}
    # Metrics 설정 (Prometheus)
    metrics:
      export:
        enabled: true
        url: ${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT}

    # Logs 설정 (Loki) - Spring Boot 3.4.0 이상에서 사용 가능
    logging:
      endpoint: ${OTEL_EXPORTER_OTLP_LOGS_ENDPOINT}
      compression: gzip
      timeout: 10s

  # 메트릭스
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99

  prometheus:
    metrics:
      export:
        enabled: ${PROMETHEUS_ENABLED:true}
