# 토큰_설정.http 사용
### 리뷰조회
# @no-cookie-jar
@alcoholId=209
GET {{host}}/api/v1/reviews/{{alcoholId}}
Authorization: Bearer {{accessToken}}

### 나의리뷰조회
GET {{host}}/api/v1/reviews/me/{{alcoholId}}
Authorization: Bearer {{accessToken}}
