### 토큰 발급 (일반)
# @no-cookie-jar
POST {{host}}/api/v1/oauth/login
Content-Type: application/json

{
  "email": "rkdtkfma@naver.com",
  "socialType": "KAKAO",
  "gender": "",
  "age": ""
}

> {%
    //토큰을 전역변수로 저장
    client.global.set("accessToken", response.body.data.accessToken);
%}


### 리뷰조회
# @no-cookie-jar
@alcoholId=209
GET {{host}}/api/v1/reviews/{{alcoholId}}
Authorization: Bearer {{accessToken}}

### 나의리뷰조회
GET {{host}}/api/v1/reviews/me/{{alcoholId}}
Authorization: Bearer {{accessToken}}
