### 토큰 발급 (일반)
POST {{host}}/api/v1/oauth/login
Content-Type: application/json

{
  "email": "rkdtkfma@naver.com",
  "socialType": "KAKAO",
  "gender": "",
  "age":""
}

> {%
    //토큰을 전역변수로 저장
    client.global.set("accessToken", response.body.data.accessToken);
%}


### 리뷰 상세 조회
@reviewId = 12
GET {{host}}/api/v1/reviews/detail/{{reviewId}}
Authorization: Bearer {{accessToken}}
