### 토큰 발급 (일반)
POST {{host}}/api/v1/oauth/login
Content-Type: application/json

{
  "email": "dev.bottle-note@gmail.com",
  "socialType": "GOOGLE",
  "gender": "",
  "age": ""
}

> {%
    //토큰을 전역변수로 저장
    client.global.set("accessToken", response.body.data.accessToken);
%}


### 사용자 디바이스 토큰 등록

POST {{host}}/push/token
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "deviceToken": "deviceToken",
}
