### 토큰 발급 (일반)
POST {{host}}/api/v1/oauth/login
Content-Type: application/json

{
  "email": "dev.bottle-note@gmail.com",
  "socialType": "GOOGLE",
  "gender": "MALE",
  "age": 25
}

> {%
    //토큰을 전역변수로 저장
    client.global.set("accessToken", response.body.data.accessToken);
%}


### 위스키 목록 조회
GET {{host}}/api/v1/alcohols/search?category=SINGLE_MALT&cursor=1&pageSize=1
Authorization: Bearer {{accessToken}}


### 위스키 조회 상세 조회
GET {{host}}/api/v1/alcohols/1
Authorization: Bearer {{accessToken}}

### 카테고리 조회
GET {{host}}/api/v1/alcohols/categories
