### 토큰이 없을 경우 발생하는 예외 예제
@alcoholId = 209
GET {{host}}/api/v1/rating/{{alcoholId}}
Content-Type: application/json


### 토큰이 없을 경우 발생하는 예외 예제
GET {{host}}/api/v1/rating/{{alcoholId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}
