INSERT INTO country (kor_name, eng_name, continent, description)
VALUES ('스코틀랜드/로우랜드', 'Scotland/Lowlands', '유럽', '가벼운 맛이 특징인 로우랜드 위스키'),
       ('스코틀랜드/하이랜드', 'Scotland/Highlands', '유럽', '맛의 다양성이 특징인 하이랜드 위스키, 해안의 짠맛부터 달콤하고 과일 맛까지'),
       ('스코틀랜드/아일레이', 'Scotland/Islay', '유럽', '강렬한 피트 맛과 연기 맛이 특징인 아일레이 위스키'),
       ('스코틀랜드/아일랜드', 'Scotland/Islands', '유럽', '풍부하고 복잡한 맛, 아일레이를 제외한 섬 지역 위스키'),
       ('스코틀랜드/스페이사이드', 'Scotland/Speyside', '유럽', '과일 맛이 강하고 부드러운 스페이사이드 위스키'),
       ('스코틀랜드/캠벨타운', 'Scotland/Campbeltown', '유럽', '풍미가 강하고 소금기가 있는 캠벨타운 위스키'),
       ('인도', 'India', '아시아', '다양한 스타일의 위스키를 생산하는 인도'),
       ('일본', 'Japan', '아시아', '섬세하고 균형 잡힌 맛의 일본 위스키'),
       ('미국', 'United States', '북아메리카', '버번과 테네시 위스키를 포함한 다양한 스타일'),
       ('아일랜드', 'Ireland', '유럽', '부드럽고 향긋한 아일랜드 위스키'),
       ('프랑스', 'France', '유럽', '주로 브랜디와 와인 생산지로 유명하지만 위스키도 생산'),
       ('스웨덴', 'Sweden', '유럽', '실험적인 방법으로 만드는 스웨덴 위스키'),
       ('덴마크', 'Denmark', '유럽', '전통적이고 현대적인 방식을 결합한 덴마크 위스키'),
       ('영국', 'United Kingdom', '유럽', '전통적인 영국 스타일의 위스키'),
       ('캐나다', 'Canada', '북아메리카', '라이 위스키가 유명한 캐나다'),
       ('네덜란드', 'Netherlands', '유럽', '유럽 스타일의 위스키를 제조하는 네덜란드'),
       ('독일', 'Germany', '유럽', '다양한 지역 위스키가 생산되는 독일'),
       ('체코', 'Czech Republic', '유럽', '새로운 위스키 생산지로 떠오르는 체코'),
       ('오스트레일리아', 'Australia', '오세아니아', '현대적인 방식으로 위스키를 생산하는 오스트레일리아'),
       ('이스라엘', 'Israel', '아시아', '독특한 기후에서 생산되는 이스라엘의 위스키'),
       ('스위스', 'Switzerland', '유럽', '소규모로 생산되는 스위스 위스키'),
       ('웨일즈', 'Wales', '유럽', '전통적인 방법으로 생산되는 웨일즈의 위스키'),
       ('타이완', 'Taiwan', '아시아', '고품질의 위스키를 생산하는 타이완'),
       ('필란드', 'Finland', '유럽', '추운 기후에서 생산되는 필란드 위스키');


INSERT INTO distillery(kor_name, eng_name)
VALUES ('글래스고 디스틸러리', 'The Glasgow Distillery Co.'),
       ('노크두', 'Knockdhu'),
       ('아드벡', 'Ardbeg'),
       ('아란', 'Arran'),
       ('에버라워', 'Aberlour'),
       ('블렌드', 'blend'),
       ('아므르트', 'Amrut'),
       ('에버펠디', 'Aberfeldy'),
       ('아사카', 'Asaka'),
       ('야마자키', 'Yamazaki'),
       ('오첸토샨', 'Auchentoshan'),
       ('와일드 터키 디스틸러리', 'Wild Turkey Distillery'),
       ('요이치', 'Yoichi'),
       ('우드퍼드 리저브', 'Woodford Reserve'),
       ('울프번', 'Wolfburn'),
       ('웨스트랜드 디스틸러리', 'Westland Distillery'),
       ('위도 제인 디스틸러리', 'Widow Jane Distillery'),
       ('윌렛 디스틸러리', 'Willett Distillery'),
       ('툴리바딘', 'Tullibardine'),
       ('쿨리', 'Cooley'),
       ('페터케언', 'Fettercairn'),
       ('에이가시마 슈조', 'Eigashima Shuzo'),
       ('글렌알라키', 'Glenallachie'),
       ('위슬피그', 'WhistlePig'),
       ('아드모어', 'Ardmore'),
       ('아드나머칸', 'Ardnamurchan'),
       ('바렌겜', 'Warenghem'),
       ('올트모어', 'Aultmore'),
       ('발블레어', 'Balblair'),
       ('발코니스 디스틸링', 'Balcones Distilling'),
       ('에드라도어', 'Edradour'),
       ('발베니', 'Balvenie'),
       ('바렐 크래프트 스피릿', 'Barrell Craft Spirits'),
       ('벤 네비스', 'Ben Nevis'),
       ('벤리아크', 'BenRiach'),
       ('벤린네스', 'Benrinnes'),
       ('벤로마크', 'Benromach'),
       ('베르그슬라겐스 데스틸레리', 'Bergslagens Destilleri'),
       ('블라드녹', 'Bladnoch'),
       ('블레어 애솔', 'Blair Athol'),
       ('버팔로 트레이스 디스틸러리', 'Buffalo Trace Distillery'),
       ('보우모어', 'Bowmore'),
       ('브라운스테인', 'Braunstein'),
       ('브루이클라디', 'Bruichladdich'),
       ('버나베인', 'Bunnahabhain'),
       ('부시밀스', 'Bushmills'),
       ('카올 일라', 'Caol Ila'),
       ('카퍼도니치', 'Caperdonich'),
       ('카드후', 'Cardhu'),
       ('치치부', 'Chichibu'),
       ('클레이 디스틸러리', 'Cley Distillery'),
       ('클로나킬티 디스틸러리', 'Clonakilty Distillery'),
       ('클리넬리시', 'Clynelish'),
       ('크래간모어', 'Cragganmore'),
       ('크레이겔라키', 'Craigellachie'),
       ('데일루에인', 'Dailuaine'),
       ('달모어', 'Dalmore'),
       ('달위니', 'Dalwhinnie'),
       ('딘스턴', 'Deanston'),
       ('딩글 위스키 디스틸러리', 'The Dingle Whiskey Distillery');
