### 토큰 발급
POST {{host}}/api/v1/oauth/login
Content-Type: application/json

{
  "email": "juye@gmail.com",
  "socialType": "GOOGLE",
  "gender": "",
  "age": ""
}

> {%
    //토큰을 전역변수로 저장
    client.global.set("accessToken", response.body.data.accessToken);
%}

### 자신을  신고 할 수 없다.
POST  {{host}}/api/v1/reports/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId" : 2,
  "reportUserId" : 2,
  "type" : "OTHER",
  "content" : "신고 내용 쏼라 쏼라 쏼라 "
}

### 사용자 신고
POST  {{host}}/api/v1/reports/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId" : 2,
  "reportUserId" : 3,
  "type" : "OTHER",
  "content" : "신고 내용 쏼라 쏼라 쏼라 "
}
