### 토큰 발급
POST {{host}}/api/v1/oauth/login
Content-Type: application/json

{
  "email": "juye@gmail.com",
  "socialType": "GOOGLE",
  "gender": "",
  "age": ""
}

> {%
    //토큰을 전역변수로 저장
    client.global.set("accessToken", response.body.data.accessToken);
%}

### 게스트 사용자가 마이페이지를 조회한다.
GET {{host}}/api/v1/mypage/1

### 로그인 이용자의 마이 페이지를 조회한다.
GET {{host}}/api/v1/mypage/8
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 타인의 마이페이지를 조회한다.
GET {{host}}/api/v1/mypage/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 존재하지 않는 사용자의 마이페이지를 조회한다.
GET {{host}}/api/v1/mypage/99999
Content-Type: application/json
Authorization: Bearer {{accessToken}}
