### 현재 사용자 정보 조회
GET {{host}}/api/v1/users/current
Authorization: Bearer {{accessToken}}

### 닉네임 변경
PATCH  {{host}}/api/v1/users/nickname
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "nickName": "juye123"
}

### 프로필 이미지 변경
PATCH  {{host}}/api/v1/users/profile-image
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "viewUrl": "http://example.com/new-profile-image2.jpg"
}
