insert into regions (kor_name, eng_name, continent, description)
values ('호주', 'Australia', null, '오세아니아에 위치한 나라로 다양한 위스키를 생산.'),
	   ('핀란드', 'Finland', null, '북유럽에 위치한 나라로 청정한 자연환경을 자랑.'),
	   ('프랑스', 'France', null, '와인과 브랜디로 유명한 유럽의 나라.'),
	   ('타이완', 'Taiwan', null, '고품질의 위스키로 유명한 동아시아의 섬나라.'),
	   ('캐나다', 'Canada', null, '위스키 생산이 활발한 북미의 나라.'),
	   ('체코', 'Czech Republic', null, '중앙유럽에 위치한 나라로 맥주로도 유명.'),
	   ('일본', 'Japan', null, '전통과 현대가 조화된 동아시아의 섬나라.'),
	   ('인도', 'India', null, '다양한 문화와 역사를 지닌 남아시아의 나라.'),
	   ('이스라엘', 'Israel', null, '중동에 위치한 나라로 와인과 위스키 생산이 증가.'),
	   ('웨일즈', 'Wales', null, '영국의 구성국 중 하나로 독자적인 위스키 생산.'),
	   ('영국', 'United Kingdom', null, '다양한 위스키 지역을 가진 나라.'),
	   ('아일랜드', 'Ireland', null, '풍부한 전통을 지닌 위스키의 본고장 중 하나입니다.'),
	   ('아이슬란드', 'Iceland', null, '청정한 자연환경과 독특한 술 문화를 가진 섬나라입니다.'),
	   ('스코틀랜드/캠벨타운', 'Scotland/Campbeltown', null, '스코틀랜드의 위스키 지역 중 하나로 해안가에 위치한 반도 형태의 지역입니다.'),
	   ('스코틀랜드/아일라', 'Scotland/Islay', null, '피트위스키의 대표 생산지입니다. 스모키한맛이 특징인 위스키로 유명한 섬입니다.'),
	   ('스코틀랜드/스페이사이드 ', 'Scotland/Speyside', null, '스코틀랜드의 중심부에 위치하고있습니다. 더프타운에 다양한 증류소들이 있습니다.'),
	   ('스코틀랜드/로우랜드', 'Scotland/Lowlands', null, '부드럽고 가벼운 맛이 특징인 위스키로 유명합니다.'),
	   ('스코틀랜드/기타섬', 'Scotland/Islands', null, '다양한 섬에서 독특한 맛의 위스키를 생산하고 있습니다.'),
	   ('스코틀랜드', 'Scotland/', null, '위스키의 본고장으로 다양한 스타일의 위스키를 생산합니다.'),
	   ('스코트랜드/하이랜드', 'Scotland/Highlands', null, '스코틀랜드 북부 지역으로 섬세한 맛의 위스키로 유명.'),
	   ('스위스', 'Switzerland', null, '알프스 산맥을 배경으로 한 유럽의 나라입니다.'),
	   ('스웨덴', 'Sweden', null, '북유럽에 위치한 나라로 맥주와 위스키 생산 증가하고 있습니다.'),
	   ('미국', 'United States', null, '다양한 스타일의 위스키를 생산하는 나라. 주로 켄터키의 버번위스키가 유명합니다.'),
	   ('독일', 'Germany', null, '맥주로 유명한 나라로 위스키 생산도 활발합니다.'),
	   ('덴마크', 'Denmark', null, '북유럽에 위치한 나라로 고유의 위스키를 생산합니다.'),
	   ('네덜란드', 'Netherlands', null, '맥주와 진으로 유명한 나라로 위스키 생산도 증가하고 있습니다.');

insert into distilleries (kor_name, eng_name, logo_img_url)
values ('글래스고', 'The Glasgow Distillery Co.', null),
	   ('글렌 그란트', 'Glen Grant', null),
	   ('글렌 기어리', 'Glen Garioch', null),
	   ('글렌 모레이', 'Glen Moray', null),
	   ('글렌 스코샤', 'Glen Scotia', null),
	   ('글렌 스페이', 'Glen Spey', null),
	   ('글렌 엘스', 'Glen Els', null),
	   ('글렌 엘진', 'Glen Elgin', null),
	   ('글렌가일', 'Glengyle', null),
	   ('글렌고인', 'Glengoyne', null),
	   ('글렌글라쏘', 'Glenglassaugh', null),
	   ('글렌달로', 'Glendalough Distillery', null),
	   ('글렌드로낙', 'Glendronach', null),
	   ('글렌로시', 'Glenlossie', null),
	   ('글렌로티스', 'Glenrothes', null),
	   ('글렌리벳', 'Glenlivet', null),
	   ('글렌모렌지', 'Glenmorangie', null),
	   ('글렌알라키', 'Glenallachie', null),
	   ('글렌카담', 'Glencadam', null),
	   ('글렌킨치', 'Glenkinchie', null),
	   ('글렌터렛', 'Glenturret', null),
	   ('글렌파클라스', 'Glenfarclas', null),
	   ('글렌피딕', 'Glenfiddich', null),
	   ('글리나', 'Glina Destillerie', null),
	   ('녹듀', 'Knockdhu', null),
	   ('뉴 리브 티스틸링', 'New Riff Distilling', null),
	   ('뉴 리프 디스틸링', 'New Riff Distilling', null),
	   ('달루인', 'Dailuaine', null),
	   ('달모어', 'Dalmore', null),
	   ('달위니', 'Dalwhinnie', null),
	   ('더프타운', 'Dufftown', null),
	   ('딘스톤', 'Deanston', null),
	   ('딩글', 'The Dingle Whiskey Distillery', null),
	   ('라가불린', 'Lagavulin', null),
	   ('라세이', 'Raasay Distillery', null),
	   ('라프로익', 'Laphroaig', null),
	   ('로얄 로크나가', 'Royal Lochnagar', null),
	   ('로얄 브라클라', 'Royal Brackla', null),
	   ('로크몬드', 'Loch Lomond', null),
	   ('루겐브로이', 'Rugenbräu', null),
	   ('링크우드', 'Linkwood', null),
	   ('마르스 신슈', 'The Mars Shinshu Distillery', null),
	   ('맥더프', 'Macduff', null),
	   ('맥미라', 'Mackmyra', null),
	   ('맥캘란', 'Macallan', null),
	   ('메이커스마크', 'Maker''s Mark Distillery, Inc.', null),
	   ('미들턴', 'Midleton (1975-)', null),
	   ('미야기쿄', 'Miyagikyo', null),
	   ('믹터스', 'Michter''s Distillery', null),
	   ('밀크 앤 허니', 'Milk & Honey Whisky Distillery', null),
	   ('밀톤더프', 'Miltonduff', null),
	   ('바렐 크래프트 스피릿', 'Barrell Craft Spirits', null),
	   ('발베니', 'Balvenie', null),
	   ('발블레어', 'Balblair', null),
	   ('발코네스', 'Balcones Distilling', null),
	   ('버팔로 트레이스', 'Buffalo Trace Distillery', null),
	   ('베르그슬라겐스', 'Bergslagens Destilleri', null),
	   ('벤 네비스', 'Ben Nevis', null),
	   ('벤로막', 'Benromach', null),
	   ('벤리네스', 'Benrinnes', null),
	   ('벤리악', 'BenRiach', null),
	   ('보모어', 'Bowmore', null),
	   ('부나하벤', 'Bunnahabhain', null),
	   ('부시밀', 'Bushmills', null),
	   ('브라우레이 로커', 'Brauerei Locher', null),
	   ('브라운 포 맨', 'Brown-Forman Distillery', null),
	   ('브라운슈타인', 'Braunstein', null),
	   ('브룩라디', 'Bruichladdich', null),
	   ('블라드녹', 'Bladnoch', null),
	   ('블레어 아톨', 'Blair Athol', null),
	   ('설리반 코브', 'Sullivans Cove', null),
	   ('세인트 킬리안', 'St. Kilian Distillers', null),
	   ('스뫼겐', 'Smögen', null),
	   ('스무스 앰블러 스피릿', 'Smooth Ambler Spirits', null),
	   ('스카파', 'Scapa', null),
	   ('스타워드', 'Starward', null),
	   ('스터닝', 'Stauning Whisky', null),
	   ('스트라스밀', 'Strathmill', null),
	   ('스트라티슬라', 'Strathisla', null),
	   ('스페이번', 'Speyburn', null),
	   ('스페이사이드', 'Speyside Distillery', null),
	   ('스프링뱅크', 'Springbank', null),
	   ('실리스', 'Slyrs', null),
	   ('아드나머칸', 'Ardnamurchan', null),
	   ('아드모어', 'Ardmore', null),
	   ('아드벡', 'Ardbeg', null),
	   ('아란', 'Arran', null),
	   ('아벨라워', 'Aberlour', null),
	   ('아사카', 'Asaka', null),
	   ('암룻', 'Amrut', null),
	   ('애버펠디', 'Aberfeldy', null),
	   ('야마자키', 'Yamazaki', null),
	   ('에드라두르', 'Edradour', null),
	   ('에드라두어', 'Edradour', null),
	   ('에이가시마 슈조', 'Eigashima Shuzo', null),
	   ('오반', 'Oban', null),
	   ('오켄토션', 'Auchentoshan', null),
	   ('와렝햄', 'Warenghem', null),
	   ('와일드 터키', 'Wild Turkey Distillery', null),
	   ('요이치', 'Yoichi', null),
	   ('우드포드 리저브', 'Woodford Reserve', null),
	   ('울트모어', 'Aultmore', null),
	   ('울프번', 'Wolfburn', null),
	   ('월렛', 'Willett Distillery', null),
	   ('웨스트랜드', 'Westland Distillery', null),
	   ('위도우 제인', 'Widow Jane Distillery', null),
	   ('잭다니엘', 'Jack Daniel''s', null),
	   ('존', 'John Distilleries', null),
	   ('주라', 'Isle of Jura', null),
	   ('쥐담', 'Zuidam Distillery', null),
	   ('짐 빔', 'Jim Beam', null),
	   ('츠누키', 'Tsunuki', null),
	   ('치치부', 'Chichibu', null),
	   ('카듀', 'Cardhu', null),
	   ('카발란', 'Kavalan', null),
	   ('카퍼도니히', 'Caperdonich', null),
	   ('쿨레이', 'Cooley', null),
	   ('쿨리', 'Cooley', null),
	   ('쿨일라', 'Caol Ila', null),
	   ('크라겐모어', 'Cragganmore', null),
	   ('크라이겔라키', 'Craigellachie', null),
	   ('크라이넬리쉬', 'Clynelish', null),
	   ('클레이', 'Cley Distillery', null),
	   ('클로나킬티', 'Clonakilty Distillery', null),
	   ('킬호만', 'Kilchoman', null),
	   ('탈라모어 듀', 'Tullamore Dew (2014 - present)', null),
	   ('탈리스커', 'Talisker', null),
	   ('탐나불린', 'Tamnavulin', null),
	   ('탐듀', 'Tamdhu', null),
	   ('터틸타운 스피리츠', 'Tuthilltown Spirits', null),
	   ('테렌펠리', 'Teerenpeli', null),
	   ('토마틴', 'Tomatin', null),
	   ('토모어', 'Tormore', null),
	   ('토민타울', 'Tomintoul', null),
	   ('토버모리', 'Tobermory', null),
	   ('툴리바딘', 'Tullibardine', null),
	   ('티니닉', 'Teaninich', null),
	   ('틸링', 'Teeling Whiskey Distillery', null),
	   ('페터케른', 'Fettercairn', null),
	   ('펜데린', 'Penderyn Distillery', null),
	   ('포 로지스', 'Four Roses Distillery', null),
	   ('풀티니', 'Pulteney', null),
	   ('하이 코스트', 'High Coast Distillery', null),
	   ('하이랜드 파크', 'Highland Park', null),
	   ('하쿠슈', 'Hakushu', null),
	   ('헤븐힐', 'Heaven Hill Distilleries, Inc.', null),
	   ('후지 코텐바', 'Fuji Gotemba', null),
	   ('휘슬피그', 'WhistlePig', null),
	   ('휘슬피거', 'WhistlePager', null),
	   ('ETC', 'ETC', null);

insert into alcohols (kor_name, eng_name, abv, type, kor_category, eng_category, category_group, region_id,
					 distillery_id, age, cask, image_url)
values ('라이터스 티얼즈 레드 헤드', 'Writers'' Tears Red Head', '46', 'WHISKY', '싱글 몰트', 'Single Malt', 'SINGLE_MALT', 12, 150,
		null, 'Oloroso Sherry Butts', 'https://static.whiskybase.com/storage/whiskies/1/8/3881/318643-big.jpg'),
	   ('라이터스 티얼즈 더블 오크', 'Writers'' Tears Double Oak', '46', 'WHISKY', '블렌디드', 'Blend', 'BLEND', 12, 47, null,
		'American & French Oak', 'https://static.whiskybase.com/storage/whiskies/1/3/1308/282645-big.jpg'),
	   ('라이터스 티얼즈 코퍼 팟', 'Writers'' Tears Copper Pot', '40', 'WHISKY', '블렌디드 몰트', 'Blended Malt', 'BLENDED_MALT', 12,
		150, null, 'Bourbon Barrels', 'https://static.whiskybase.com/storage/whiskies/7/7/471/189958-big.jpg'),
	   ('VAT 69 블렌디드 스카치 위스키', 'VAT 69 Blended Scotch Whisky', '40', 'WHISKY', '블렌디드', 'Blend', 'BLEND', 16, 150, null,
		null, 'https://static.whiskybase.com/storage/whiskies/8/1/189/246095-big.jpg'),
	   ('툴리바딘 소버린', 'Tullibardine Sovereign', '43', 'WHISKY', '싱글 몰트', 'Single Malt', 'SINGLE_MALT', 20, 137, null,
		'1st fill bourbon barrel', 'https://static.whiskybase.com/storage/whiskies/1/7/4450/390659-big.jpg'),
	   ('탈라모어 듀 XO', 'Tullamore Dew XO', '43', 'WHISKY', '블렌디드', 'Blend', 'BLEND', 12, 127, null,
		'Caribbean Rum Cask Finish', 'https://static.whiskybase.com/storage/whiskies/1/0/9073/192995-big.jpg'),
	   ('탈라모어 듀 더 레전더리 아이리시 위스키', 'Tullamore Dew The Legendary Irish Whiskey', '40', 'WHISKY', '블렌디드', 'Blend', 'BLEND',
		12, 47, null, null, 'https://static.whiskybase.com/storage/whiskies/4/0/935/122228-big.jpg'),
	   ('탈라모어 듀 사이다 캐스크 피니시', 'Tullamore Dew Cider Cask Finish', '40', 'WHISKY', '블렌디드', 'Blend', 'BLEND', 12, 47, null,
		'Cider Cask Finish', 'https://static.whiskybase.com/storage/whiskies/6/9/408/192993-big.jpg'),
	   ('탈라모어 듀 14년', 'Tullamore Dew 14y', '41.3', 'WHISKY', '싱글 몰트', 'Single Malt', 'SINGLE_MALT', 12, 47, '14',
		'Bourbon, Oloroso Sherry, Port, Madeira Finish',
		'https://static.whiskybase.com/storage/whiskies/7/8/743/201942-big.jpg'),
	   ('탈라모어 듀 12년', 'Tullamore Dew 12y', '40', 'WHISKY', '블렌디드', 'Blend', 'BLEND', 12, 47, '12',
		'Ex-Bourbon & Oloroso Sherry Casks', 'https://static.whiskybase.com/storage/whiskies/8/1/442/229572-big.jpg'),
	   ('토모어 16년', 'Tormore 16y', '48', 'WHISKY', '싱글 몰트', 'Single Malt', 'SINGLE_MALT', 16, 134, '16',
		'American Oak Cask', 'https://static.whiskybase.com/storage/whiskies/2/0/0044/349731-big.jpg'),
	   ('토모어 14년', 'Tormore 14y', '43', 'WHISKY', '싱글 몰트', 'Single Malt', 'SINGLE_MALT', 16, 134, '14', 'American Oak',
		'https://static.whiskybase.com/storage/whiskies/4/6/006/87125-big.jpg'),
	   ('토민타울 피티탱', 'Tomintoul With A Peaty Tang', '40', 'WHISKY', '싱글 몰트', 'Single Malt', 'SINGLE_MALT', 16, 135, null,
		null, 'https://static.whiskybase.com/storage/whiskies/1/2/2408/373021-big.jpg'),
	   ('토민타울 시가몰트', 'Tomintoul Cigar Malt', '43', 'WHISKY', '싱글 몰트', 'Single Malt', 'SINGLE_MALT', 16, 135, null,
		'Oloroso', 'https://static.whiskybase.com/storage/whiskies/1/6/7902/372433-big.jpg'),
	   ('토민타울 16년', 'Tomintoul 16y', '40', 'WHISKY', '싱글 몰트', 'Single Malt', 'SINGLE_MALT', 16, 135, '16', null,
		'https://static.whiskybase.com/storage/whiskies/6/7/387/106575-big.jpg'),
	   ('토민타울 14년', 'Tomintoul 14y', '46', 'WHISKY', '싱글 몰트', 'Single Malt', 'SINGLE_MALT', 16, 135, '14',
		'American oak ex-bourbon', 'https://static.whiskybase.com/storage/whiskies/2/0/0756/133825-big.jpg'),
	   ('토민타울 10년', 'Tomintoul 10y', '40', 'WHISKY', '싱글 몰트', 'Single Malt', 'SINGLE_MALT', 16, 135, '10',
		'American oak ex-bourbon barrel', 'https://static.whiskybase.com/storage/whiskies/1/2/2573/205398-big.jpg'),
	   ('아벨라워 18년', 'Aberlour 18y', '43', 'WHISKY', '싱글 몰트', 'Single Malt', 'SINGLE_MALT', 16, 89, '18',
		'Am. & Eur. Oak + 1st-Fill PX & Oloroso Finish',
		'https://static.whiskybase.com/storage/whiskies/2/3/7131/424101-big.jpg'),
	   ('포트 샬롯 10년', 'Port Charlotte 10y', '50', 'WHISKY', '싱글 몰트', 'Single Malt', 'SINGLE_MALT', 15, 69, '10', null,
		'https://static.whiskybase.com/storage/whiskies/1/1/2320/201819-big.jpg'),
	   ('카듀 엠버 록', 'Cardhu Amber Rock', '40', 'WHISKY', '싱글 몰트', 'Single Malt', 'SINGLE_MALT', 16, 115, null,
		'Bourbon Cask', 'https://static.whiskybase.com/storage/whiskies/5/4/607/343007-big.jpg'),
	   ('탈라모어 듀 더 레전더리 아이리시 위스키', 'Tullamore Dew The Legendary Irish Whiskey', '40', 'WHISKY', '블렌디드', 'Blend', 'BLEND',
		12, 47, null, null, 'https://static.whiskybase.com/storage/whiskies/4/0/935/122228-big.jpg'),
	   ('아드나머칸 AD', 'Ardnamurchan AD/', '46.8', 'WHISKY', '싱글 몰트', 'Single Malt', 'SINGLE_MALT', 20, 85, null,
		'Bourbon & Sherry', 'https://static.whiskybase.com/storage/whiskies/2/2/5270/415209-big.jpg'),
	   ('울프번 10년', 'Wolfburn 10y', '46', 'WHISKY', '싱글 몰트', 'Single Malt', 'SINGLE_MALT', 20, 104, '10',
		'Oloroso Sherry Hogsheads', 'https://static.whiskybase.com/storage/whiskies/2/3/0518/412215-big.jpg');
