name: Qodana
on:
  workflow_dispatch: # 워크플로우를 수동으로 실행할 수 있게 합니다.
  pull_request: # PR이 생성될 때 워크플로우를 실행합니다.
  push:
    branches: # 아래 지정된 브랜치에 push가 발생할 때 워크플로우를 실행합니다.
      - main # 'main' 브랜치
      - 'releases/*' # 'releases/'로 시작하는 모든 브랜치

jobs:
  qodana:
    runs-on: ubuntu-latest # 작업이 실행될 가상 환경을 지정합니다.
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # 실제 PR 커밋을 체크아웃합니다 (merge 커밋이 아님).
          fetch-depth: 0  # PR 분석을 위해 전체 기록이 필요합니다.
      - name: 'Qodana Scan' # Qodana 코드 품질 스캔을 실행합니다.
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }} # Qodana 사용을 위한 토큰입니다.
