name: Code Formatting

on:
  push:
    branches:
      - '**'
    paths:
      - '**.java'
      - 'build.gradle'
      - 'gradle/libs.versions.toml'

jobs:
  format:
    runs-on: ubuntu-latest

    # [skip ci]가 포함된 커밋 메시지는 실행하지 않음 (무한 루프 방지)
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Spotless Apply
        run: ./gradlew spotlessApply

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: apply code formatting [skip ci]'
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
