name: Deploy to Dev

on:
  workflow_call:
    inputs:
      IMAGE_TAG:
        required: true
        type: string
    secrets:
      GIT_ACCESS_TOKEN:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Update submodules
        run: |
          git submodule update --init --recursive
          git submodule update --remote


      - name: Set ECR credentials and Env file
        id: set-credentials
        run: |
          ECR_ACCESS_KEY=$(grep "ECR_ACCESS_KEY:" git.environment-variables/deploy/aws/ecr/properties.yaml | awk '{print $2}')
          ECR_SECRET_ACCESS_KEY=$(grep "ECR_SECRET_ACCESS_KEY:" git.environment-variables/deploy/aws/ecr/properties.yaml | awk '{print $2}')
          ECR_REGION=$(grep "ECR_REGION:" git.environment-variables/deploy/aws/ecr/properties.yaml | awk '{print $2}')
          ECR_REGISTRY=$(grep "ECR_REGISTRY:" git.environment-variables/deploy/aws/ecr/properties.yaml | awk '{print $2}')

          echo "AWS_ACCESS_KEY_ID=$ECR_ACCESS_KEY" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$ECR_SECRET_ACCESS_KEY" >> $GITHUB_ENV
          echo "AWS_REGION=$ECR_REGION" >> $GITHUB_ENV
          echo "ECR_REGISTRY=$ECR_REGISTRY" >> $GITHUB_ENV
          echo "region=$ECR_REGION" >> $GITHUB_OUTPUT
          echo "registry=$ECR_REGISTRY" >> $GITHUB_OUTPUT

          ENV_FILE=$(cat git.environment-variables/deploy/.env.dev | base64 -w 0)
          echo "$ENV_FILE" >> $GITHUB_OUTPUT


      - name: Save Docker image to tar
        run: |
          docker pull ${{ steps.set-credentials.outputs.registry }}/bottle-note-api:${{ inputs.IMAGE_TAG }}
          docker save ${{ steps.set-credentials.outputs.registry }}/bottle-note-api:${{ inputs.IMAGE_TAG }} > bottle-note-image.tar

      - name: Transfer files to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.DEV_SSH_KEY }}
          port: ${{ secrets.DEV_SERVER_PORT }}
          source:
            - bottle-note-image.tar
            - git.environment-variables/deploy/.env.dev
          target: /home/ubuntu/app/bottle-note/

      - name: Deploy on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.DEV_SSH_KEY }}
          port: ${{ secrets.DEV_SERVER_PORT }}
          script: |
            cd /home/ubuntu/app/bottle-note/
            docker stop test-bottle-note || true
            docker rm test-bottle-note || true
            docker load < bottle-note-image.tar
            docker run -d \
              --name test-bottle-note \
              -p 30002:30001 \
              -e TZ=Asia/Seoul \
              -e SPRING_PROFILES_ACTIVE=dev \
              --env-file .env.dev \
              --restart unless-stopped \
              ${{ steps.set-credentials.outputs.registry }}/bottle-note-api:${{ inputs.IMAGE_TAG }}
            rm bottle-note-image.tar
