name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Notification
        run: |
          echo "이것은 프로덕션(prod) 환경 배포 파일입니다."
          echo "배포할 이미지 태그: ${{ github.event.inputs.image_tag }}"

      # 여기에 실제 배포 로직을 추가할 수 있습니다.
