name: Dev Deploy Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    types: [ closed ]
    branches:
      - dev

# 동시에 여러 워크플로우가 실행되지 않도록 설정
concurrency:
  group: "dev-deploy"
  cancel-in-progress: false

jobs:
  build-and-push:
    # PR이 merge되었을 때만 실행
    # if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest  # 워크플로우는 최신 Ubuntu 환경에서 실행됩니다.
    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      ## JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      ## 원격 환경에 코드 복사
      - name: copy project # ssh key를 이용해 현재 푸시된 소스를 서버에 복사한다.
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete # rsync 명령어 옵션
          remote_path: /home/ubuntu/app/bottle-note
          remote_host: ${{ secrets.DEV_SERVER_IP }}
          remote_port: ${{ secrets.DEV_SERVER_PORT }}
          remote_user: ubuntu
          remote_key: ${{ secrets.DEV_SSH_KEY }}

      ## deploy setup
      - name: deploy setup and gradle build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          port: ${{ secrets.DEV_SERVER_PORT }}
          username: ubuntu
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd /home/ubuntu/app/bottle-note
            touch  /home/ubuntu/app/bottle-note/src/main/resources/application-dev.yml
            echo "${{ secrets.APPLICATION_DEV }}" | base64 --decode > src/main/resources/application-dev.yml  
            chmod +x gradlew
            ./gradlew build

      ## 개발 도커 실행
      - name: docker compose up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          port: ${{ secrets.DEV_SERVER_PORT }}
          username: ubuntu
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd /home/ubuntu/app/bottle-note
            docker stop dev-bottle-note || true
            docker rm dev-bottle-note || true
            docker-compose -f docker-compose-dev.yml up -d --no-deps --build dev-bottle-note
            docker image prune -f
