name: Dev CI Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev

concurrency:
  group: "dev-ci"
  cancel-in-progress: true

jobs:
  dev_ci:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0
        options: --privileged
        ports:
          - 1234:1234
        env:
          DOCKER_TLS_CERTDIR: ""

    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2"

    steps:
      - name: echo
        run: |
          echo "Branch: ${{ github.event.pull_request.base.ref || github.ref_name }}"

      - name: Checkout Code (코드 체크아웃)
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Setup JDK (자바 설정)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle Cache (그래들 캐시 설정)
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Dependencies (종속성 설치)
        run: ./gradlew dependencies

      - name: Run Integration Tests (통합 테스트 실행)
        run: ./gradlew integrationTest

      - name: Run Unit Tests (단위 테스트 실행)
        run: ./gradlew unitTest

      - name: Build Project (프로젝트 빌드)
        run: ./gradlew build

      - name: Store Test Results (테스트 결과 저장)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            build/reports/tests/
            build/reports/integration-tests/

      - name: Publish Test Report (테스트 보고서 발행)
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
