name: Dev Continuous Integration

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

concurrency:
  group: "dev-ci"
  cancel-in-progress: false

jobs:
  dev_ci:

    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
        options: --privileged
        ports:
          - 1234:1234
        env:
          DOCKER_TLS_CERTDIR: ""
    steps:
      # 코드 체크아웃
      - name: 코드 체크아웃  # 소스 코드를 체크아웃하는 단계
        uses: actions/checkout@v4

      ## JDK 17 설정
      - name: JDK 설정  # JDK 17 설정 단계
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      ## Gradle 캐시 설정
      - name: Gradle 캐시 설정  # Gradle 캐시를 설정하는 단계
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: 종속성 설치
        run: ./gradlew dependencies

      - name: 빌드 및 테스트
        run: ./gradlew build

      - name: 테스트 실행
        run: ./gradlew allTests
