name: Build and Push to ECR

on:
  push:
    branches:
      - feature/279

concurrency:
  group: "ecr-upload"
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      region: ${{ steps.set-credentials.outputs.region }}
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
      - name: Update submodules
        run: |
          git submodule update --init --recursive
          git submodule update --remote
      - name: setup env file
        run: cp git.environment-variables/deploy/.env .env
      - name: docker build
        run: |
          # Dockerfile 빌드
          docker build -t bottle-note-api .
          # 빌드 결과 확인
          echo "==== 빌드된 이미지 정보 ===="
          docker images | grep bottle-note-api
