# export DOCKER_HOST="unix:///var/folders/x4/rbwfkbt52mg_xvm4gwvmjrpc0000gn/T/podman/podman-machine-default-api.sock"
# act workflow_dispatch -W .github/workflows/test-secrets-loading.yml --secret-file .secrets
name: Test Secrets Loading

on:
  workflow_dispatch:

jobs:
  test-load-secrets:
    runs-on: ubuntu-latest
    steps:
      # 1. 레포지토리 체크아웃 (서브모듈 포함)
      - name: 레포지토리 체크아웃 (서브모듈 포함)
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

      # 2. Oracle 인스턴스 환경변수 로드
      - name: Oracle 인스턴스 환경변수 로드
        env:
          ENV_FILE: git.environment-variables/deploy/oracle/application-node-1.env
        run: |
          echo "📄 환경변수 파일 로드 중..."
          if [ ! -f "$ENV_FILE" ]; then
            echo "❌ 환경변수 파일을 찾을 수 없습니다: $ENV_FILE"
            exit 1
          fi

          # .env 파일 읽어서 환경변수로 설정
          while IFS='=' read -r key value || [ -n "$key" ]; do
            # 빈 줄이나 주석 스킵
            [[ -z "$key" || "$key" == \#* ]] && continue

            # 모든 값 마스킹 (키만 노출)
            echo "::add-mask::${value}"

            # GitHub 환경변수로 설정
            echo "${key}=${value}" >> $GITHUB_ENV
            echo "  ✅ $key 로드됨"
          done < "$ENV_FILE"

          echo ""
          echo "✅ 환경변수 로드 완료"


      # 3. SSH 개인키 파일 로드
      - name: SSH 개인키 파일 로드
        env:
          KEY_FILE: git.environment-variables/deploy/oracle/keys/node-1.pem
        run: |
          echo "🔑 SSH 개인키 파일 로드 중..."

          if [ ! -f "$KEY_FILE" ]; then
            echo "❌ SSH 키 파일을 찾을 수 없습니다: $KEY_FILE"
            exit 1
          fi

          # SSH 키 전체 내용을 환경변수로 저장
          SSH_KEY=$(cat "$KEY_FILE")

          # SSH 키의 각 줄 마스킹
          echo "$SSH_KEY" | while IFS= read -r line; do
            [ -n "$line" ] && echo "::add-mask::${line}"
          done

          # 멀티라인 환경변수로 설정
          {
            echo "SSH_PRIVATE_KEY<<EOF_SSH_KEY"
            cat "$KEY_FILE"
            echo "EOF_SSH_KEY"
          } >> $GITHUB_ENV

          echo "✅ SSH 개인키 로드 완료"


      # 4. SSH 접속 테스트
      - name: SSH 접속 테스트
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.INSTANCE_NETWORK_PUBLIC_IP }}
          username: ${{ env.INSTANCE_HOST_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ env.INSTANCE_NETWORK_PORT }}
          script: |
            echo "=== 📡 Oracle 인스턴스 접속 성공 ==="
            echo ""
            echo "🐧 시스템 정보:"
            uname -a
            echo ""
            echo "📋 OS 릴리즈 정보:"
            cat /etc/os-release
            echo ""
            echo "=== ✅ SSH 접속 검증 완료 ==="
